Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using ElevkårSida.Models;

namespace ElevkårSida.Controllers
{
    public class LoginController : Controller
    {
        string connectionString = ConfigurationManager.ConnectionStrings["ElevDBString"].ConnectionString;

        [HttpGet]
        public ActionResult Index()
        {
            return View(new UserModel());
        }

        [HttpPost]
        public ActionResult Index(UserModel userLogin, string Email, string Password)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                DataTable loginInfo = new DataTable();
                sqlCon.Open();
                string query = "SELECT UserId FROM Tbl_Users WHERE Username = @Username AND Password = @Password";
                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@Username", userLogin.Username);
                sqlDa.SelectCommand.Parameters.AddWithValue("@Password", userLogin.Password);
                sqlDa.Fill(loginInfo);

                if (loginInfo.Rows.Count > 0)
                {
                    Session["LoginId"] = int.Parse(loginInfo.Rows[0]["UserId"].ToString());
                }
                else
                {
                    ViewBag.LoginResult = "Fel lösenord eller epostaddress";
                    return View();
                }
            }

            return RedirectToAction("Index", "Forum");
        }
        public ActionResult Logout()
        {
            Session["LoginId"] = null;
            return RedirectToAction("Index", "Forum");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Elevkåren</title>
    <link href="~/Content/css/Styles.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
var RootUrl = '@Url.Content("~/")';
    </script>
</head>
<body>
    <div id="menu">
        @if (Session["LoginId"] == null)
        {
            <a id="AdminLogin" href="@Url.Action("Index","Login")">Logga in (Admin)</a>
        }
        <img src="~/Content/images/download.jpg" />
        <ul>
            @if (Session["LoginId"] == null)
            {
                <li><a href="@Url.Action("Index","Forum")">Hem</a></li>
                <li><a href="@Url.Action("Feedback","Forum")">Feedback</a></li>
                <li><a href="https://ebas.gymnasiet.sverigeselevkarer.se/signups/index/500">Gå med</a></li>
            }
            else
            {
                <li><a href="@Url.Action("Index","Forum")">Hem</a></li>
                <li><a href="@Url.Action("Index","Admin")">Dashboard</a></li>
                <li><a href="@Url.Action("Logout","Login")">Logga ut</a></li>
            }
        </ul>
    </div>
    <div id="container">
        <header>
            <div id="hamMenuIcon" onclick="toggleMenu()">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <h1>@ViewBag.Title</h1>
        </header>
        @RenderBody()

    </div>
    <script src="~/Scripts/Functions.js"></script>
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Elevkåren</title>
    <link href="~/Content/css/Styles.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
var RootUrl = '@Url.Content("~/")';
    </script>
</head>
<body>
    <div id="menu">
        @if (Session["LoginId"] == null)
        {
            <a id="AdminLogin" href="@Url.Action("Index","Login")">Logga in (Admin)</a>
        }
        <img src="~/Content/images/download.jpg" />
        <ul>
            @if (Session["LoginId"] == null)
            {
                <li><a href="@Url.Action("Index","Forum")">Hem</a></li>
                <li><a href="@Url.Action("Feedback","Forum")">Feedback</a></li>
                <li><a href="https://ebas.gymnasiet.sverigeselevkarer.se/signups/index/500">Gå med</a></li>
            }
            else
            {
                <li><a href="@Url.Action("Index","Forum")">Hem</a></li>
                <li><a href="@Url.Action("Index","Admin")">Dashboard</a></li>
                <li><a href="@Url.Action("Logout","Login")">Logga ut</a></li>
            }
        </ul>
    </div>
    <div id="container" class="adminContainer">
        <header id="AdminHeaderNotShadow">
            <div id="hamMenuIcon" onclick="toggleMenu()">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <h1>@ViewBag.Title</h1>
            <div id="AdminHeader">
                <a href="@Url.Action("Index", "Admin")"><i class="material-icons">arrow_back</i><span>Tillbaka</span></a>
            </div>
        </header>

        @RenderBody()
    </div>
    <script src="~/Scripts/Functions.js"></script>
</body>
</html>
